import Utils from './utils.js'

const utils = new Utils()

export default class Superluminary {
	constructor(){
	}

	_random_lookup(table, number_of_results=1) {
		let result = utils.getRandom(table, number_of_results)
		let raw_result = result
		if (number_of_results == 1) {
			result = result[0]
		} else {			
			result = utils.arrayToSentence(result)	
		}
		return {
			"roll": null,
			"raw_result": raw_result,
			"result": result,
			"table": table
		}
	}

	_d10_lookup(table){
		let roll = utils.rollDice(1, 10)
		return {
			"roll": roll.total,
			"result": table[roll.total],
			"table": table
		}
	}
	
	_d100_lookup(table){
		let roll = utils.d100()
		return {
			"roll": roll,
			"result": table[roll],
			"table": table
		}
	}

	pocket_dimension(){
		let table = {
			1: "Arachnoid nest",
			2: "Imploding wormhole",
			3: "Sideways-space",
			4: "Synaesthesia and psychedelic weirdness",
			5: "The dreamsea",
			6: "The machine realm",
			7: "The microverse",
			8: "The negative zone",
			9: "The phantom zone",
			10: "The river of time"
		}		
		return this._d10_lookup(table)
	}

	predator_special_abilities(){
		let table = [
			"Acid for Blood",
			"Armoured Carapace",
			"Batlike Wings",
			"Battle Frenzy",
			"Blend into Surroundings",
			"Body Spikes",
			"Breathe Fire",
			"Breathe Poisonous Gas",
			"Drain Life Energy",
			"Electricity Field",
			"Enhanced Senses",
			"Face Tentacles",
			"Feathered Wings",
			"Feels No Pain",
			"Four Arms",
			"Giant-Sized",
			"Grappling Tentacles",
			"Horns",
			"Horrendous Stench",
			"Immune to Energy Weapons",
			"Immune to Kinetic Weapons",
			"Immune to Psionics",
			"Incredible Speed",
			"Incredible Strength",
			"nfectious Disease",
			"Insectoid Wings",
			"Lashing Tail",
			"Lightning Reflexes",
			"Mind Control Tendrils",
			"Phase into Hyperspace",
			"Pincer Claws",
			"Plasma Bolt",
			"Poisonous Sting",
			"Poo Out a Minion",
			"Powerful Leap",
			"Psychic Shriek",
			"Radioactive",
			"Regenerate",
			"Return from the Dead Even Angrier",
			"Shapeshifter",
			"Spit Acid",
			"Telekinesis",
			"Telepath",
			"Teleport",
			"Terrifying Appearance",
			"Tough Hide",
			"Trail of Slime",
			"Two Heads",
			"Use Technology",
			"Web Spinner"
		]
		return this._random_lookup(table, 3)	
	}

	predator_flaw(){
		let table = [
			"Accidentally Destroys Surroundings",
			"Afraid of Fire",
			"Afraid of Sunlight",
			"Afraid of Water",
			"Attacks Own Injuries When Hurt",
			"Attacks Own Reflection",
			"Berserk Rage",
			"Blind",
			"Blind Spot",
			"Brittle Bones",
			"Can Only Sense Heat Patterns",
			"Can Only Sense Movement",
			"Can’t Control Powers",
			"Can’t Get Back Up if Knocked Over",
			"Can’t Leave Own Territory",
			"Can’t Resist a Direct Challenge",
			"Can’t Turn Around Easily",
			"Chink in Armour",
			"Claustrophobic",
			"Clumsy Giant",
			"Deaf",
			"Defers to Alpha",
			"Desperately Hungry",
			"Easily Tricked",
			"Extremely Flammable",
			"Extremely Heavy",
			"Fascinated by Shiny Things",
			"Flees from Stronger Foes",
			"Immediately Feeds on Downed Victims",
			"Old Injury",
			"Overconfident",
			"Powers Need Time to Recharge",
			"Reckless Curiosity",
			"Roars Loudly All the Time",
			"Runs and Hides When Startled",
			"Sensitive to Bright Lights",
			"Sensitive to Loud Noises",
			"Short Reach",
			"Short-Sighted",
			"Slow Mover",
			"Smells Bad",
			"Stupid",
			"Stymied by Obstacles",
			"Tires Quickly",
			"Very Short Memory",
			"Vulnerable to Bacteria",
			"Vulnerable to Bladed Weapons",
			"Vulnerable to Fire",
			"Vulnerable to Psionics",
			"Vulnerable to Radiation"
		]
		return this._random_lookup(table)
	}

	npc_personality_trait(){
		let table = [
			"Addicted to Spice",
			"Always Betray Rebel Scum",
			"Ambitious",
			"Argumentative",
			"Arrogant",
			"At One with the Universe",
			"Bad Loser",
			"Barbaric",
			"Bitter",
			"Blunt",
			"Brave",
			"Cautious",
			"Civilised",
			"Cold",
			"Competitive",
			"Confident",
			"Conformist",
			"Cowardly",
			"Creative",
			"Cruel",
			"Curious",
			"Cynical",
			"Dependent on Technology",
			"Desperate",
			"Determined",
			"Diplomatic",
			"Disorganised",
			"Distrusts Telepaths",
			"Driven",
			"Easy-Going",
			"Efficient",
			"End Justifies the Means",
			"Fanatical",
			"Fascinated by the Exotic",
			"Forgiving",
			"Friendly",
			"Generous",
			"Gentle",
			"Greedy",
			"Grouchy",
			"Hardened",
			"Hates Robots",
			"Honest",
			"Hot Tempered",
			"Idealistic",
			"Ignorant",
			"Impatient",
			"Impulsive",
			"Inscrutable",
			"Intellectual",
			"Lazy",
			"Liar",
			"Loyal",
			"Mischievous",
			"Modest",
			"Naive",
			"Nervous",
			"Noble",
			"No Love for the Empire",
			"Optimist",
			"Overanalytical",
			"Pacifist",
			"Paranoid",
			"Perceptive",
			"Perfectionist",
			"Pessimist",
			"Philosophical",
			"Practical",
			"Prefers Robots to Humans",
			"Principled",
			"Proud",
			"Progressive",
			"Rationalist",
			"Rebel",
			"Reckless",
			"Sarcastic",
			"Secret Imperial Collaborator",
			"Seen a Lot of Strange Stuff",
			"Selfish",
			"Sensitive",
			"Serious",
			"Sheltered Upbringing",
			"Shy",
			"Slapdash",
			"Stubborn",
			"Superstitious",
			"Suspicious",
			"Talkative",
			"Technophobic",
			"Traditionalist",
			"Treacherous",
			"Trusting",
			"Uncertain",
			"Unflappable",
			"Unpredictable",
			"Unprincipled",
			"Vengeful",
			"Warlike",
			"Weak",
			"Willed",
			"Xenophobic"
		]
		
		return this._random_lookup(table)
	}
	
	cargo(){
		let table = {
			1: "1,000 copies of owner’s manual for a 2053 Iron Falcon",
			2: "A giant bomb that begins counting down as soon as the characters open or scan it",
			3: "Air filters",
			4: "Alien crystals that amplify psychic abilities",
			5: "Alien crystals that nullify psychic abilities",
			6: "Alien fruit (delicious)",
			7: "Alien fruit (trippy)",
			8: "Ammo/energy clips",
			9: "Armour (Kevlar)",
		   10: "Armour (plasteel)",
		   11: "Armour (powered)",
		   12: "Batteries",
		   13: "Bone/ivory",
		   14: "Books (antique)",
		   15: "Camera drones",
		   16: "Carpets and fine rugs",
		   17: "Circuitboards",
		   18: "Circuitboards infested with ferrus worms",
		   19: "Clothing (cheap)",
		   20: "Clothing (fine)",
		   21: "Clothing (haute couture)",
		   22: "Complete archive of holovids",
		   23: "Components for a giant supercomputer",
		   24: "Computer chips",
		   25: "Confidential files belonging to the local authorities",
		   26: "Credit chips (forged)",
		   27: "Credit chips (real but marked)",
		   28: "Cybernetic limbs",
		   29: "Dead bodies (frozen)",
		   30: "Drugs (combat)",
		   31: "Drugs (medical)",
		   32: "Drugs (recreational)",
		   33: "Dry rations",
		   34: "Empty!",
		   35: "Engine parts",
		   36: "Exotic alien plants",
		   37: "Explosives",
		   38: "Fine art",
		   39: "Flatpack furniture",
		   40: "Food paste",
		   41: "Food pills",
		   42: "Frozen meat",
		   43: "Fuel cells",
		   44: "Gas canisters",
		   45: "Gems and jewellery (cheap)",
		   46: "Gems and jewellery (expensive)",
		   47: "Gold bars",
		   48: "Hidden refugees",
		   49: "Holofilm records of a doomed expedition to an alien world",
		   50: "Holovid recording equipment",		   
		   51: "Home entertainment systems",
		   52: "Hyperdrive coils",
		   53: "Imperial propaganda",
		   54: "Infamous bounty hunter Bandem Tor, frozen in carbonite",
		   55: "Jetpacks",
		   56: "Liquor",
		   57: "Live cattle",
		   58: "Lovebots",
		   59: "Medical supplies",
		   60: "Metal ore",
		   61: "Miniature nuclear generators",
		   62: "Necrophage eggs",
		   63: "Oil drums",
		   64: "Personal computers",
		   65: "Plastic sheeting",
		   66: "Platinum bars",
		   67: "Poison gas canisters",
		   68: "Quantum amplifier",
		   69: "Radiation capsules",
		   70: "Rocketbikes",
		   71: "Rotmeat spyders",
		   72: "Scanners",
		   73: "Scrap metal (cheap)",
		   74: "Scrap metal (expensive)",
		   75: "Scrap metal (irradiated)",
		   76: "Security equipment",
		   77: "Silver bars",
		   78: "Skeletons and tissue samples of an unknown alien species",
		   79: "Small animals frozen for experimentation",
		   80: "Space suits (basic)",
		   81: "Space suits (combat)",
		   82: "Space suits (damaged)",
		   83: "Spare robot parts",
		   84: "Sports equipment",
		   85: "Statue of the Emperor (disassembled)",
		   86: "Strange alien idol (cursed)",
		   87: "Stuffed animals/hunting trophies",
		   88: "Synthi-grain",
		   89: "Terraforming equipment",
		   90: "Tools",
		   91: "Uniforms (military)",
		   92: "Uniforms (security)",
		   93: "Uniforms (takeout restaurant)",
		   94: "Various urns and artifacts from a xenoarchaeological dig site",
		   95: "Vat-grown organs",
		   96: "Water",
		   97: "Weapons (military-grade)",
		   98: "Weapons (personal defence)",
		   99: "Weapons (superheavy)",
		  100: "Wood"
		}
		return this._d100_lookup(table)
	}
	
	ship_trait(){}
	
	weapon(){
		let table = {
			1: "Acid spitter",
			2: "Annihilator pistol",
			3: "Anti-tank grenades",
			4: "Antimatter ray",
			5: "Assault rifle with armour-piercing ammo",
			6: "Assault rifle with heat-seeking AI rounds",
			7: "Autolaser",
			8: "Battleglove",
			9: "Black light gun",
		   10: "Blast pistol with red dot laser sight",
		   11: "Carbon pistol",
		   12: "Chainsaw",
		   13: "Continuous beam projector",
		   14: "Death ray",
		   15: "Disintegrator",
		   16: "Drillgun",
		   17: "Electro-whip",
		   18: "Electrolaser",
		   19: "EMP blaster",
		   20: "Energy bow",
		   21: "Flamethrower",
		   22: "Flash-bang grenades",
		   23: "Flechette pistol",
		   24: "Force bubble projector",
		   25: "Forearm blaster",
		   26: "Frag grenades",
		   27: "Freeze ray",
		   28: "Fusion gun",
		   29: "Gatling blaster",
		   30: "Grappling hook gun",
		   31: "Gravity gun",
		   32: "Green energy ring",
		   33: "Harpoon gun",
		   34: "Haywire grenades",
		   35: "Heat ray",
		   36: "Heavy cutting laser",
		   37: "Heavy mag pistol",
		   38: "Heavy repeating blaster",
		   39: "Hypervelocity shotgun",
		   40: "Hypno-ray",
		   41: "Implosion grenades",
		   42: "Incendiary grenades",
		   43: "Ion blaster",
		   44: "Kinetic energy grenades",
		   45: "Laser cannon",
		   46: "Laser disguised as everyday object",
		   47: "Laserblade",
		   48: "Lightning gun",
		   49: "Living gun that fires teeth",
		   50: "Massive bomb",
		   51: "Combi-weapon (roll twice and combine them into one weapon)",
		   52: "Microwaver",
		   53: "Missile launcher",
		   54: "Mk 1 laser pistol with heavy power pack",
		   55: "Molecular disassembler",
		   56: "Mono-molecular edge katana",
		   57: "Monofilament shredder",
		   58: "Nanotoxin injector",
		   59: "Nerve gas",
		   60: "Neural scrambler",
		   61: "Nova cannon",
		   62: "Nullifier",
		   63: "Pain inducer",
		   64: "Panic ray",
		   65: "Paralysis ray",
		   66: "Particle accelerator",
		   67: "Plague rifle",
		   68: "Plasma carbine",
		   69: "Power field",
		   70: "Precision laser rifle with invisible tracing beam",
		   71: "Pulse rifle with underslung grenade launcher",
		   72: "Pump-action shotgun",
		   73: "Quantum deconstructor",
		   74: "Railgun",
		   75: "Ramjet sniper rifle with laser sight",
		   76: "Remote-controlled gun drone",
		   77: "Revolver (antique)",
		   78: "Sabre (antique)",
		   79: "Shardgun",
		   80: "Shock mace",
		   81: "Shoulder-mounted autocannon",
		   82: "Shuriken rifle (full auto)",
		   83: "Smartgun",
		   84: "Smoke grenades",
		   85: "Snarenet launcher",
		   86: "Sonic disruptor",
		   87: "Starfire photon cannon",
		   88: "Stinger pistol",
		   89: "Strontium beamer",
		   90: "Stun gun",
		   91: "Submachine gun",
		   92: "Subsonic coilgun (totally silent)",
		   93: "Teleportation gun",
		   94: "Thermic lance",
		   95: "Thunder blaster",
		   96: "Tron disc",
		   97: "Turbolaser",
		   98: "Twin autopistols",
		   99: "Vibro-halberd with built-in blaster",
		  100: "Wrist-mounted rocket launcher"
		}
		return this._d100_lookup(table)
	}
	
	world_planet_type(){}
	
	world_primary_inhabitants(){}
	
	war_machine_trait(){
		let table = [
			"Alternate Movement Mode",
			"Anti-Air Missiles",
			"Armour Is Too Strong for Blasters",
			"Assault Ramp",
			"Bioweapon Spray",
			"Blind Spot at Rear",
			"Boneshaker",
			"Bristling with Weapons",
			"Broadcast Array",
			"Camouflaged",
			"Cargo-Gripping Claws",
			"Cloaking Field",
			"Covered in Spikes",
			"Defence Batteries",
			"Detachable Spy Drone",
			"Dozer Blade",
			"Drag Chutes",
			"EMP Field",
			"Escape Pod",
			"False Markings",
			"Fuel Guzzler",
			"Impossibly Sleek",
			"Incredibly Loud Engine",
			"Invisibility Field Activates When Stationary",
			"Kirby Dot Energy Field",
			"Looks Like a Mythological Creature",
			"Main Gun Needs to Recharge",
			"Melee Attack Mode",
			"Mine Layer",
			"Multisensor",
			"Obsolete Model",
			"Onboard AI",
			"Outrageous Spoiler",
			"Piloted Remotely",
			"Pop-Up Flamethrowers",
			"Prominent Oversized Engine",
			"Rear-Firing Laser",
			"Rocket Thrusters",
			"Roll Cage",
			"Signal Jammer",
			"Smaller Vehicle Emerges from the Wreckage When Destroyed",
			"Smoke Launchers",
			"Spews Noxious Fumes",
			"Stealth Mode",
			"Stripped-Down Armour",
			"Transforms into Different Type of Vehicle",
			"Turbo Boosters",
			"Unreliable Autopilot",
			"Unstable Power Source",
			"Vulnerable Exhaust Port	"
		]
		
		return this._random_lookup(table)
	}

	city_encounter(){}

	space_encounter(){}

	wilderness_encoutner(){}	

/*

		let table = {
			1: "",
			2: "",
			3: "",
			4: "",
			5: "",
			6: "",
			7: "",
			8: "",
			9: "",
		   10: "",
		   11: "",
		   12: "",
		   13: "",
		   14: "",
		   15: "",
		   16: "",
		   17: "",
		   18: "",
		   19: "",
		   20: "",
		   21: "",
		   22: "",
		   23: "",
		   24: "",
		   25: "",
		   26: "",
		   27: "",
		   28: "",
		   29: "",
		   30: "",
		   31: "",
		   32: "",
		   33: "",
		   34: "",
		   35: "",
		   36: "",
		   37: "",
		   38: "",
		   39: "",
		   40: "",
		   41: "",
		   42: "",
		   43: "",
		   44: "",
		   45: "",
		   46: "",
		   47: "",
		   48: "",
		   49: "",
		   50: "",
		   51: "",
		   52: "",
		   53: "",
		   54: "",
		   55: "",
		   56: "",
		   57: "",
		   58: "",
		   59: "",
		   60: "",
		   61: "",
		   62: "",
		   63: "",
		   64: "",
		   65: "",
		   66: "",
		   67: "",
		   68: "",
		   69: "",
		   70: "",
		   71: "",
		   72: "",
		   73: "",
		   74: "",
		   75: "",
		   76: "",
		   77: "",
		   78: "",
		   79: "",
		   80: "",
		   81: "",
		   82: "",
		   83: "",
		   84: "",
		   85: "",
		   86: "",
		   87: "",
		   88: "",
		   89: "",
		   90: "",
		   91: "",
		   92: "",
		   93: "",
		   94: "",
		   95: "",
		   96: "",
		   97: "",
		   98: "",
		   99: "",
		  100: ""
		}

*/
	
}