import Utils from './utils.js'

const utils = new Utils()

export default class Superluminary {
	constructor(){
	}

	cargo(){
		let table = {
			1: "1,000 copies of owner’s manual for a 2053 Iron Falcon",
			2: "A giant bomb that begins counting down as soon as the characters open or scan it",
			3: "Air filters",
			4: "Alien crystals that amplify psychic abilities",
			5: "Alien crystals that nullify psychic abilities",
			6: "Alien fruit (delicious)",
			7: "Alien fruit (trippy)",
			8: "Ammo/energy clips",
			9: "Armour (Kevlar)",
		   10: "Armour (plasteel)",
		   11: "Armour (powered)",
		   12: "Batteries",
		   13: "Bone/ivory",
		   14: "Books (antique)",
		   15: "Camera drones",
		   16: "Carpets and fine rugs",
		   17: "Circuitboards",
		   18: "Circuitboards infested with ferrus worms",
		   19: "Clothing (cheap)",
		   20: "Clothing (fine)",
		   21: "Clothing (haute couture)",
		   22: "Complete archive of holovids",
		   23: "Components for a giant supercomputer",
		   24: "Computer chips",
		   25: "Confidential files belonging to the local authorities",
		   26: "Credit chips (forged)",
		   27: "Credit chips (real but marked)",
		   28: "Cybernetic limbs",
		   29: "Dead bodies (frozen)",
		   30: "Drugs (combat)",
		   31: "Drugs (medical)",
		   32: "Drugs (recreational)",
		   33: "Dry rations",
		   34: "Empty!",
		   35: "Engine parts",
		   36: "Exotic alien plants",
		   37: "Explosives",
		   38: "Fine art",
		   39: "Flatpack furniture",
		   40: "Food paste",
		   41: "Food pills",
		   42: "Frozen meat",
		   43: "Fuel cells",
		   44: "Gas canisters",
		   45: "Gems and jewellery (cheap)",
		   46: "Gems and jewellery (expensive)",
		   47: "Gold bars",
		   48: "Hidden refugees",
		   49: "Holofilm records of a doomed expedition to an alien world",
		   50: "Holovid recording equipment",		   
		   51: "Home entertainment systems",
		   52: "Hyperdrive coils",
		   53: "Imperial propaganda",
		   54: "Infamous bounty hunter Bandem Tor, frozen in carbonite",
		   55: "Jetpacks",
		   56: "Liquor",
		   57: "Live cattle",
		   58: "Lovebots",
		   59: "Medical supplies",
		   60: "Metal ore",
		   61: "Miniature nuclear generators",
		   62: "Necrophage eggs",
		   63: "Oil drums",
		   64: "Personal computers",
		   65: "Plastic sheeting",
		   66: "Platinum bars",
		   67: "Poison gas canisters",
		   68: "Quantum amplifier",
		   69: "Radiation capsules",
		   70: "Rocketbikes",
		   71: "Rotmeat spyders",
		   72: "Scanners",
		   73: "Scrap metal (cheap)",
		   74: "Scrap metal (expensive)",
		   75: "Scrap metal (irradiated)",
		   76: "Security equipment",
		   77: "Silver bars",
		   78: "Skeletons and tissue samples of an unknown alien species",
		   79: "Small animals frozen for experimentation",
		   80: "Space suits (basic)",
		   81: "Space suits (combat)",
		   82: "Space suits (damaged)",
		   83: "Spare robot parts",
		   84: "Sports equipment",
		   85: "Statue of the Emperor (disassembled)",
		   86: "Strange alien idol (cursed)",
		   87: "Stuffed animals/hunting trophies",
		   88: "Synthi-grain",
		   89: "Terraforming equipment",
		   90: "Tools",
		   91: "Uniforms (military)",
		   92: "Uniforms (security)",
		   93: "Uniforms (takeout restaurant)",
		   94: "Various urns and artifacts from a xenoarchaeological dig site",
		   95: "Vat-grown organs",
		   96: "Water",
		   97: "Weapons (military-grade)",
		   98: "Weapons (personal defence)",
		   99: "Weapons (superheavy)",
		  100: "Wood"
		}
		return utils.table_d100_lookup(table)
	}

	pocket_dimension(){
		let table = {
			1: "Arachnoid nest",
			2: "Imploding wormhole",
			3: "Sideways-space",
			4: "Synaesthesia and psychedelic weirdness",
			5: "The dreamsea",
			6: "The machine realm",
			7: "The microverse",
			8: "The negative zone",
			9: "The phantom zone",
			10: "The river of time"
		}		
		return utils.table_d10_lookup(table)
	}

	predator_special_abilities(){
		let table = [
			"Acid for Blood",
			"Armoured Carapace",
			"Batlike Wings",
			"Battle Frenzy",
			"Blend into Surroundings",
			"Body Spikes",
			"Breathe Fire",
			"Breathe Poisonous Gas",
			"Drain Life Energy",
			"Electricity Field",
			"Enhanced Senses",
			"Face Tentacles",
			"Feathered Wings",
			"Feels No Pain",
			"Four Arms",
			"Giant-Sized",
			"Grappling Tentacles",
			"Horns",
			"Horrendous Stench",
			"Immune to Energy Weapons",
			"Immune to Kinetic Weapons",
			"Immune to Psionics",
			"Incredible Speed",
			"Incredible Strength",
			"nfectious Disease",
			"Insectoid Wings",
			"Lashing Tail",
			"Lightning Reflexes",
			"Mind Control Tendrils",
			"Phase into Hyperspace",
			"Pincer Claws",
			"Plasma Bolt",
			"Poisonous Sting",
			"Poo Out a Minion",
			"Powerful Leap",
			"Psychic Shriek",
			"Radioactive",
			"Regenerate",
			"Return from the Dead Even Angrier",
			"Shapeshifter",
			"Spit Acid",
			"Telekinesis",
			"Telepath",
			"Teleport",
			"Terrifying Appearance",
			"Tough Hide",
			"Trail of Slime",
			"Two Heads",
			"Use Technology",
			"Web Spinner"
		]
		return utils.table_random_lookup(table, 3)	
	}

	predator_flaw(){
		let table = [
			"Accidentally Destroys Surroundings",
			"Afraid of Fire",
			"Afraid of Sunlight",
			"Afraid of Water",
			"Attacks Own Injuries When Hurt",
			"Attacks Own Reflection",
			"Berserk Rage",
			"Blind",
			"Blind Spot",
			"Brittle Bones",
			"Can Only Sense Heat Patterns",
			"Can Only Sense Movement",
			"Can’t Control Powers",
			"Can’t Get Back Up if Knocked Over",
			"Can’t Leave Own Territory",
			"Can’t Resist a Direct Challenge",
			"Can’t Turn Around Easily",
			"Chink in Armour",
			"Claustrophobic",
			"Clumsy Giant",
			"Deaf",
			"Defers to Alpha",
			"Desperately Hungry",
			"Easily Tricked",
			"Extremely Flammable",
			"Extremely Heavy",
			"Fascinated by Shiny Things",
			"Flees from Stronger Foes",
			"Immediately Feeds on Downed Victims",
			"Old Injury",
			"Overconfident",
			"Powers Need Time to Recharge",
			"Reckless Curiosity",
			"Roars Loudly All the Time",
			"Runs and Hides When Startled",
			"Sensitive to Bright Lights",
			"Sensitive to Loud Noises",
			"Short Reach",
			"Short-Sighted",
			"Slow Mover",
			"Smells Bad",
			"Stupid",
			"Stymied by Obstacles",
			"Tires Quickly",
			"Very Short Memory",
			"Vulnerable to Bacteria",
			"Vulnerable to Bladed Weapons",
			"Vulnerable to Fire",
			"Vulnerable to Psionics",
			"Vulnerable to Radiation"
		]
		return utils.table_random_lookup(table)
	}

	npc_personality_trait(){
		let table = [
			"Addicted to Spice",
			"Always Betray Rebel Scum",
			"Ambitious",
			"Argumentative",
			"Arrogant",
			"At One with the Universe",
			"Bad Loser",
			"Barbaric",
			"Bitter",
			"Blunt",
			"Brave",
			"Cautious",
			"Civilised",
			"Cold",
			"Competitive",
			"Confident",
			"Conformist",
			"Cowardly",
			"Creative",
			"Cruel",
			"Curious",
			"Cynical",
			"Dependent on Technology",
			"Desperate",
			"Determined",
			"Diplomatic",
			"Disorganised",
			"Distrusts Telepaths",
			"Driven",
			"Easy-Going",
			"Efficient",
			"End Justifies the Means",
			"Fanatical",
			"Fascinated by the Exotic",
			"Forgiving",
			"Friendly",
			"Generous",
			"Gentle",
			"Greedy",
			"Grouchy",
			"Hardened",
			"Hates Robots",
			"Honest",
			"Hot Tempered",
			"Idealistic",
			"Ignorant",
			"Impatient",
			"Impulsive",
			"Inscrutable",
			"Intellectual",
			"Lazy",
			"Liar",
			"Loyal",
			"Mischievous",
			"Modest",
			"Naive",
			"Nervous",
			"Noble",
			"No Love for the Empire",
			"Optimist",
			"Overanalytical",
			"Pacifist",
			"Paranoid",
			"Perceptive",
			"Perfectionist",
			"Pessimist",
			"Philosophical",
			"Practical",
			"Prefers Robots to Humans",
			"Principled",
			"Proud",
			"Progressive",
			"Rationalist",
			"Rebel",
			"Reckless",
			"Sarcastic",
			"Secret Imperial Collaborator",
			"Seen a Lot of Strange Stuff",
			"Selfish",
			"Sensitive",
			"Serious",
			"Sheltered Upbringing",
			"Shy",
			"Slapdash",
			"Stubborn",
			"Superstitious",
			"Suspicious",
			"Talkative",
			"Technophobic",
			"Traditionalist",
			"Treacherous",
			"Trusting",
			"Uncertain",
			"Unflappable",
			"Unpredictable",
			"Unprincipled",
			"Vengeful",
			"Warlike",
			"Weak",
			"Willed",
			"Xenophobic"
		]
		
		return utils.table_random_lookup(table)
	}
	
	ship_trait(){
		let table = [
			"Anti-Laser Dispersion Field",
			"Blink Engine",
			"Boarding Pods",
			"Cluster Mines",
			"Combat Manoeuvre Wings",
			"Deceleration Ray",
			"EMP Field",
			"Forward-Firing Railgun",
			"FTL Blocking System",
			"Gatling Laser Cannon",
			"Heavily Armoured",
			"Holographic Projector",
			"Limpet Mines",
			"Mass Driver",
			"Massive Jet Thrusters",
			"Missile Deflector Shield",
			"Onboard Hacker",
			"Onboard Telepath",
			"Onboard VIP",
			"Particle Accelerator",
			"Photon Cannon",
			"Pilot Has a Grudge Against the Player Characters",
			"Pilot Is a Crack Shot",
			"Pilot Is Dead, the Ship Is Operating on Autopilot",
			"Pilot Is One Day from Retirement",
			"Pilot Is Overconfident",
			"Reinforced Ramming Spike",
			"Remote Attack Drones (Buzzsaws)",
			"Remote Attack Drones (Lasers)",
			"Repair Drones",
			"Repulsion Field",
			"Scything Laser Beam",
			"Self-Destruct Charge",
			"Self-Guiding Nukes",
			"Ship Is About to Explode",
			"Ship Is Badly Damaged from an Earlier Engagement",
			"Ship Is Leaking Fuel",
			"Ship Is Low on Ammo",
			"Sidewinder Missiles",
			"Silent Running Mode",
			"Splits into Two Smaller Ships If Destroyed",
			"Stealth Field",
			"Teleporter Ray",
			"Thermic Lance",
			"Tractor Beam",
			"Turboboosters",
			"Unbreakable Hull",
			"Unstable Plasma Reactor",
			"Valuable Cargo",
			"Vectored Intercept Engines"
		];
		return utils.table_random_lookup(table)
	}
	
	weapon(){
		let table = {
			1: "Acid spitter",
			2: "Annihilator pistol",
			3: "Anti-tank grenades",
			4: "Antimatter ray",
			5: "Assault rifle with armour-piercing ammo",
			6: "Assault rifle with heat-seeking AI rounds",
			7: "Autolaser",
			8: "Battleglove",
			9: "Black light gun",
		   10: "Blast pistol with red dot laser sight",
		   11: "Carbon pistol",
		   12: "Chainsaw",
		   13: "Continuous beam projector",
		   14: "Death ray",
		   15: "Disintegrator",
		   16: "Drillgun",
		   17: "Electro-whip",
		   18: "Electrolaser",
		   19: "EMP blaster",
		   20: "Energy bow",
		   21: "Flamethrower",
		   22: "Flash-bang grenades",
		   23: "Flechette pistol",
		   24: "Force bubble projector",
		   25: "Forearm blaster",
		   26: "Frag grenades",
		   27: "Freeze ray",
		   28: "Fusion gun",
		   29: "Gatling blaster",
		   30: "Grappling hook gun",
		   31: "Gravity gun",
		   32: "Green energy ring",
		   33: "Harpoon gun",
		   34: "Haywire grenades",
		   35: "Heat ray",
		   36: "Heavy cutting laser",
		   37: "Heavy mag pistol",
		   38: "Heavy repeating blaster",
		   39: "Hypervelocity shotgun",
		   40: "Hypno-ray",
		   41: "Implosion grenades",
		   42: "Incendiary grenades",
		   43: "Ion blaster",
		   44: "Kinetic energy grenades",
		   45: "Laser cannon",
		   46: "Laser disguised as everyday object",
		   47: "Laserblade",
		   48: "Lightning gun",
		   49: "Living gun that fires teeth",
		   50: "Massive bomb",
		   51: "Combi-weapon (roll twice and combine them into one weapon)",
		   52: "Microwaver",
		   53: "Missile launcher",
		   54: "Mk 1 laser pistol with heavy power pack",
		   55: "Molecular disassembler",
		   56: "Mono-molecular edge katana",
		   57: "Monofilament shredder",
		   58: "Nanotoxin injector",
		   59: "Nerve gas",
		   60: "Neural scrambler",
		   61: "Nova cannon",
		   62: "Nullifier",
		   63: "Pain inducer",
		   64: "Panic ray",
		   65: "Paralysis ray",
		   66: "Particle accelerator",
		   67: "Plague rifle",
		   68: "Plasma carbine",
		   69: "Power field",
		   70: "Precision laser rifle with invisible tracing beam",
		   71: "Pulse rifle with underslung grenade launcher",
		   72: "Pump-action shotgun",
		   73: "Quantum deconstructor",
		   74: "Railgun",
		   75: "Ramjet sniper rifle with laser sight",
		   76: "Remote-controlled gun drone",
		   77: "Revolver (antique)",
		   78: "Sabre (antique)",
		   79: "Shardgun",
		   80: "Shock mace",
		   81: "Shoulder-mounted autocannon",
		   82: "Shuriken rifle (full auto)",
		   83: "Smartgun",
		   84: "Smoke grenades",
		   85: "Snarenet launcher",
		   86: "Sonic disruptor",
		   87: "Starfire photon cannon",
		   88: "Stinger pistol",
		   89: "Strontium beamer",
		   90: "Stun gun",
		   91: "Submachine gun",
		   92: "Subsonic coilgun (totally silent)",
		   93: "Teleportation gun",
		   94: "Thermic lance",
		   95: "Thunder blaster",
		   96: "Tron disc",
		   97: "Turbolaser",
		   98: "Twin autopistols",
		   99: "Vibro-halberd with built-in blaster",
		  100: "Wrist-mounted rocket launcher"
		}
		return utils.table__d100_lookup(table)
	}
	
	world_planet_type(){
		let table = [
			"Agricultural world",
			"Blasted world",
			"Capital world",
			"City world",
			"Corporate world",
			"Cultured world",
			"Desert world",
			"Feudal world",
			"Gas giant",
			"Ice world",
			"Industrial world",
			"Jungle world",
			"Junk world",
			"Militarised world",
			"Mining colony",
			"Occupied world",
			"Ocean world",
			"Prison world",
			"Savage world",
			"Research colony or space station",
			"Swamp world",
			"Technoid world",
			"Theocratic world",
			"Trading world",
			"Volcanic world",
			"Wild west world",
			"Barren and lifeless rock – totally inhospitable",
			"Hot gas giant – totally inhospitable",
			"Toxic ocean world – totally inhospitable"
		]
		
		let roll = utils.rollDice(1, 100)
		
		if (roll.total == 100) {
			return utils.table_random_lookup(table, 2)
		} else {
			return utils.table_random_lookup(table)
		}			
	}
	
	world_primary_inhabitants(){}
	
	war_machine_trait(){
		let table = [
			"Alternate Movement Mode",
			"Anti-Air Missiles",
			"Armour Is Too Strong for Blasters",
			"Assault Ramp",
			"Bioweapon Spray",
			"Blind Spot at Rear",
			"Boneshaker",
			"Bristling with Weapons",
			"Broadcast Array",
			"Camouflaged",
			"Cargo-Gripping Claws",
			"Cloaking Field",
			"Covered in Spikes",
			"Defence Batteries",
			"Detachable Spy Drone",
			"Dozer Blade",
			"Drag Chutes",
			"EMP Field",
			"Escape Pod",
			"False Markings",
			"Fuel Guzzler",
			"Impossibly Sleek",
			"Incredibly Loud Engine",
			"Invisibility Field Activates When Stationary",
			"Kirby Dot Energy Field",
			"Looks Like a Mythological Creature",
			"Main Gun Needs to Recharge",
			"Melee Attack Mode",
			"Mine Layer",
			"Multisensor",
			"Obsolete Model",
			"Onboard AI",
			"Outrageous Spoiler",
			"Piloted Remotely",
			"Pop-Up Flamethrowers",
			"Prominent Oversized Engine",
			"Rear-Firing Laser",
			"Rocket Thrusters",
			"Roll Cage",
			"Signal Jammer",
			"Smaller Vehicle Emerges from the Wreckage When Destroyed",
			"Smoke Launchers",
			"Spews Noxious Fumes",
			"Stealth Mode",
			"Stripped-Down Armour",
			"Transforms into Different Type of Vehicle",
			"Turbo Boosters",
			"Unreliable Autopilot",
			"Unstable Power Source",
			"Vulnerable Exhaust Port"
		]			
		
		return utils.table_random_lookup(table)
	}

	city_encounter(){
		let table = [
			"A brown homunculus takes a shine to the characters and starts following them.",
			"A bar-room brawl involving rival gangs of space truckers spills out onto the street.",
			"A childlike but effectively omnipotent alien shapeshifter seeks the group’s help in trying to understand the society around him. If he gets bored he will start destroying things.",
			"A courier on a thrusterbike tries to serve a summons on the characters to act as witnesses in a pending discrimination suit, Gweeble v the Intergalactic Task Force Alliance.",
			"A crowd of drunken revelers attempt to make friends with the characters and draw them into the celebrations. Refusal is likely to be taken as a personal insult.",
			"A desperate group of escaped convicts (who were arrested for crimes they didn’t commit) kidnap the player characters and demand they help them get off-world.",
			"A crew of demolition robots go crazy and start smashing up the neighbourhood.",
			"A cybered-up psychopath goes on the rampage. Use the Random Weapons table on page 97 to determine his weapon of choice.",
			"A film crew recording a spectacular action sequence for the latest holovid blockbuster desperately need a volunteer from the crowd after their stuntman dies of ‘natural causes’.",
			"A firefight erupts across the street as an attempted bankrobbery is interrupted by local law enforcement. Several innocent bystanders are caught up in the crossfire.",
			"A gang of piglike thugs confront the player characters and try to cause trouble.",
			"A group of down-and-out aliens aggressively beg the characters for change.",
			"A flying noodle bar in the shape of a large boat settles down near to the characters. The owner (and much of the clientele) can be a good source of underworld gossip.",
			"A giant stonebreaker being used as a beast of burden snaps and goes on a rampage.",
			"A group of down-and-out robots aggressively beg the characters for oil.",
			"A hitman takes someone out. The player characters are now potential witnesses.",
			"A hovertruck crashes into a parked vehicle and flips over. The driver flees unharmed, but the back doors fall open to reveal... a random cargo from the table on page 95.",
			"A jetpack-wearing criminal is shot down by the cops as she tries to flee, dropping a mysterious briefcase at the characters’ feet in the process.",
			"A holocelebrity doing vox pop interviews with random passers-by approaches the player characters for a comment.",
			"A hulking brute in an ill-fitting suit tries to intimidate the characters into buying a lifetime subscription to Space magazine.",
			"A Kalgarian death leaper has just escaped from the local zoo or gladiatorial arena and is heading straight for the player characters!",
			"A lynch mob chasing a pair of mutants into a back alley.",
			"A man and a woman come running around the corner in terror, being pursued by about a dozen tox zombies.",
			"A nearby building is on fire. People inside are screaming for help.",
			"A large stampeding crowd of people separates the player characters and forces a retreat.",
			"A malfunctioning translator robot is accidentally insulting everyone it meets, and is about to get disintegrated by some Petrakian space pirates on shore leave as a result.",
			"A passer-by’s pet Snarltooth takes an instant but visceral dislike to a random player character.",
			"A roadside psychic offers to tell the characters their future... for a price.",
			"A scoundrel approaches the characters with the score of a lifetime (50% chance genuine).",
			"A speeding car smashes into the characters’ own vehicle (or nearly runs them over if they are on foot).",
			"A tentacled manipulator offers the characters a reward if they will steal a (cursed) statue of his gods from the (mob-owned) Museum of Space Trucking.",
			"A witness is being chased down by mob enforcers working for Boss Tabasco. He offers the player characters 10,000 credits if they will help.",
			"An eccentric robotechnician needs help trying to recapture an escaped hover drone that’s malfunctioning and jamming all the traffic lights in the area.",
			"An over-aggressive robocab tries to force the characters off the road (if they are driving) or pesters them for a fare (if they are walking).",
			"A man walks up to the characters, punches himself several times in the face, and then shouts for the police to have them arrested for assault.",
			"A party of rich but vulnerable Klendoshans (aloof supergeniuses with vegan powers) have become separated from their tour guide.",
			"A pickpocket grabs something off one of the player characters and attempts to flee.",
			"A rooftop sniper starts picking people off at random.",
			"A slime squid living in a giant pile of garbage lashes out in search of fresh meat.",
			"A stray power unit robot follows the characters around hoping they will adopt it.",
			"A tox zombie feasting on a fresh victim in an alleyway. It will attack if disturbed.",
			"A woman approaches the characters and asks for help. Her son has been missing for several days and she believes he has been kidnapped by some Disciples of the Black Light who have made a base deep in the undercity.",
			"An illegal ad bomb explosion gives everyone nearby a chemical addiction to some random commercial product.",
			"An overzealous police robot attempts to arrest the characters for jaywalking and/or littering.",
			"An undercover agent takes an interest in the player characters and starts following them.",
			"Architects of Pain kidnapping a bunch of homeless dudes for ‘experimentation’.",
			"An untrained telepath loses control of his power and accidentally forms a terrifying two-way mindlink with everyone around him.",
			"Black market trader offering good deals on various illegal items.",
			"‘Deathsticks? Wanna buy some deathsticks?’Food riot.",
			"Earthquake!",
			"Giant mutant rats swarm out of the sewers in search of their next victim.",
			"‘He doesn’t like you. I don’t like you, either.’ Two local toughs approach the player characters.",
			"Hoverboard-riding gangers try to drive the player characters out of their territory.",
			"‘I don’t feel too well, mister.’ A man walks up to the player characters, falls down dead, and then rises again as a tox zombie.",
			"Imperial shocktroopers storm a suspected rebel hideout.",
			"Large numbers of down-and-outs have appeared in this area recently. When asked why, they say they are fleeing a mysterious beast that has been hunting them in the undercity.",
			"Little shop of wonders offers amazing deals on incredible alien artifacts, but it won’t be here tomorrow! 50% chance each item bought is cursed or somehow malfunctioning.",
			"Massive traffic jams as far as the eye can see.",
			"Illegal pod racers zoom past, scattering pedestrians and shattering windows.",
			"Jetbike-riding gangers attempt to intimidate/attack/race with the player characters.",
			"Legendary robotic serial killer Razorclaw identifies the player characters as its next victims.",
			"Local law enforcement ask to see the group’s papers.",
			"Med-techs trying desperately to resuscitate someone who was attacked by streetgangers.",
			"Mystic penitents from Leropidus 5 seek to die an honourable death... in ritualistic battle with the player characters.",
			"‘Out of the way, meatbags!’ A pushy robot with a chip on its shoulder bumps into one of the player characters and demands an immediate apology.",
			"Radiation leak, the area must be evacuated immediately.",
			"Situationist terrorists set off a hallucinogen bomb in the middle of the street. Everyone in the crowd is affected. Roll on the Trippy Effects table on page 126 to see the result.",
			"Neighbourhood kids throwing rocks at a pack of innocent Cycloderms (one-eyed ugly herbivores).",
			"Police roadblock and full scanning operation straight ahead.",
			"Ratlike diminutive scavengers launch a hit-and-run attack on the player characters, hoping to steal away something of value.",
			"Smog rises to intolerable levels, forcing unprotected citizens to seek refuge indoors.",
			"Some very unlucky wannabe crooks attempt to mug the player characters.",
			"Supporters of the resistance having a clandestine meeting.",
			"Telepathic cops sweep the area looking for a rogue fugitive.",
			"Sudden power cut across the whole grid sector.",
			"Tech-ninjas attack!",
			"The characters are caught up in some kind of terrorist (resistance?) attack.",
			"The characters are caught up in the crossfire as two local gangs duke it out.",
			"The characters bump into one of their old friends out on the street.",
			"The characters hear gunfire around the corner. If they investigate they find a local cop lying badly wounded on the floor. He points and says, ‘They went that-a-way. Get them!’.",
			"The characters see local law enforcement roughing up some random citizen for no obvious reason.",
			"The characters stumble across an abandoned pile of 20th-century technology and kitsch.",
			"The characters’ vehicle breaks down (or, if they are on foot, a random player character badly twists their ankle in a pothole).",
			"The masked bounty hunter Obsidian flies overhead in his rocketpack, chasing up new leads on the mysterious Cabal. When he spots the characters, he approaches and asks them what they know. If he is suspicious he may have them followed or bugged.",
			"The player characters see a nasty car crash happen up ahead.",
			"Torrential rainfall, 25% chance it’s acidic.",
			"Two rival gunslingers are about to draw on each other.",
			"Violent thunderstorm.",
			"The characters bump into one of their old enemies out on the street.",
			"The characters catch a local diplomat in a compromising position.",
			"The characters see a snatch-and-grab robbery in progress across the street.",
			"The characters see one of their allies or contacts being arrested by Imperial agents.",
			"The characters stumble across an illegal gambling den.",
			"The group are harangued by a recruiter for the Church of the Secret Robot.",
			"The player characters get lost, and find themselves drifting into a bad part of town.",
			"Ticket touts have great deals on mole man opera night at the Electric Circus.",
			"Transport tube malfunction; several people are injured or killed.",
			"Vicious razorbirds swoop down from their skyscraper nests and attack the player characters, or at least try to steal their lunch.",
			"Complicated situation – roll twice."
		]
		
		return utils.table_random_lookup(table)
	}

	space_encounter(){}

	wilderness_encoutner(){}	

	name_generator() {
		let names = ["Abel","Abraham","Achilles","Achim","Ada","Adam","Adamek","Adela","Adelajda","Adelheid","Adelka","Adok","Adolf","Adolfek","Adriana","Adrianka","Agata","Agathe","Agatka","Agnes","Aja","Ala","Alan","Alanek","Albert","Albertek","Albin","Albina","Albinka","Albrecht","Alca","Aldon","Aldona","Aleksandr","Aleksy","Alena","Alenka","Ales","Alexander","Alexandr","Alexandra","Alexej","Alexius","Alfons","Alfred","Alheid","Alice","Alina","Alka","Alois","Alzbeta","Alzbetka","Amalia","Amalie","Amalka","Ambros","Ambroz","Amos","Anastazie","Anastazja","Anastazka","Anca","Andela","Andelka","Andnej","Andrea","Andreas","Andrej","Andrejka","Andulka","Aneta","Anetka","Anezka","Angelika","Ania","Anicka","Anieli","Aninka","Anja","Anka","Anna","Anne","Anneliese","Annette","Annika","Anselm","Antje","Anton","Antonie","Antonin","Antonina","Anuska","Apolena","Apolenka","Apoloniusz","Arabella","Ariadna","Armand","Armandek","Armin","Arnd","Arndt","Arno","Arnold","Arnolt","Arnost","Arnostek","Arnulf","Aron","Artur","Arturek","Asta","Astrid","August","Augustin","Augustus","Augustyn","Aurek","Aureli","Axel","Babi","Babinka","Balbina","Baltazar","Bara","Barbara","Barbel","Barbora","Barborka","Barca","Bartolomej","Barunka","Baruska","Basha","Basia","Basilej","Bazyli","Beata","Beate","Beatka","Beatrix","Beda","Bedrich","Bedrisek","Bedriska","Bela","Belinka","Belka","Ben","Bendek","Bendyk","Benedikt","Benjamin","Benoni","Berenike","Bernard","Bernd","Bernhard","Berta","Bertel","Berthold","Berticka","Bertik","Bertinka","Beta","Betka","Bettina","Betunka","Betuska","Bialas","Bialy","Birgit","Blahoslav","Blahoslava","Blanicka","Blanka","Blaza","Blazej","Blazek","Blazena","Blazenka","Blazka","Bodgana","Bodo","Bogna","Bogumil","Boguslaw","Bohda","Bohdan","Bohdana","Bohgana","Bohous","Bohumil","Bohumila","Bohumir","Bohumira","Bohuna","Bohunka","Bohus","Bohuska","Bohuslav","Bohuslava","Bolek","Boleslav","Boleslava","Bonifac","Bonifacy","Borek","Borik","Boris","Borisek","Borivoj","Boromej","Borys","Boryslaw","Boza","Bozena","Bozenka","Bozka","Branislav","Breta","Bretek","Bretik","Bretislav","Brigit","Brigita,","Brigitka","Brigitte","Bronek","Bronik","Bronislav","Bronislava","Broz","Brozik","Brunhild","Bruno","Brygid","Carsten","Casimir","Cecilie","Cecilka","Cenda","Cenek","Cestmir","Charlotte","Christa","Christian","Christin","Christina","Christof","Cibor","Cilinka","Cilka","Claudia","Clemens","Conrad","Ctibor","Ctirad","Curd","Cyprian","Cyrek","Cyryl","Czeslaw","Dagmar","Dagmarka","Dagobert","Dalek","Dalibor","Dalibora","Dalimil","Damek","Dan","Dana","Danicka","Daniel","Daniela","Danka","Danousek","Danulka","Danuska","Dara","Darina","Darinka","Darja","Darka","Dasa","Dasenka","David","Davidek","Deni","Denisa","Deniska","Detlef","Dia","Diana","Dianka","Dierk","Dieter","Dietrich","Dionizy","Dita","Ditka","Dobieslaw","Dobinka","Dobra","Dobromil","Dobromila","Dobroslav","Dobroslava","Dobry","Dodek","Dolf","Dominik","Dominika","Donat","Dora","Doreen","Dorek","Dorka","Dorle","Doroata","Dorota","Dorothea","Dorotka","Doubravka","Draha","Drahomir","Drahomira","Drahos","Drahoslav","Drahoslava","Drahuse","Drahuska","Dusan","Dusana","Dusanek","Eda","Edacek","Edda","Edeltraud","Edik","Edita","Editka","Edous","Eduard","Edvard","Edyta","Effi","Egon","Ela","Elek","Elena","Elenka","Elfriede","Elias","Elisabeth","Eliska","Elka","Elke","Elmar","Elsa","Elwira","Elzbieta","Ema","Eman","Emanek","Emanuel","Emil","Emilie","Emilka","Emma","Emmerich","Emmilian","Engelbert","Erek","Erhard","Erich","Erik","Erika","Erna","Ernst","Eryk","Ester","Esterka","Eugenia","Euzebia","Eva","Evelina","Evelinka","Evicka","Evinka","Evka","Evulka","Evuska","Evza","Evzen","Evzenek","Evzenie","Evzenka","Ewa","Eytan","Fabian","Falco","Fanka","Fanous","Fanousek","Fany","Fanynka","Fela","Feliks","Felix","Felka","Ferda","Ferdik","Ferdinand","Fieke","Filda","Filip","Filipek","Filipina","Flawiusz","Florian","Frana","Franciszka","Frandszk","Franta","Frantik","Frantina","Frantisek","Frantiska","Franz","Franziska","Frieda","Friedelind","Friederike","Friedhelm","Friedhild","Friedrich","Fritz","Fritzi","Fryderyk","Gabi","Gabin","Gabina","Gabriel","Gabriela","Gabriele","Gabrielka","Galina","Gebhard","Geli","Gerda","Gerek","Gerhard,","","Gerik","Gerlinde","Gernot","Gertraud","Gerwazy","Gisela","Gita","Gitka","Gitta","Gizela","Gizelka","Gnegon","Golo","Gottfried","Gotthold","Gottlieb","Grazyna","Gregor","Gretchen","Guido","Gunther","Gusta","Gustaf","Gustav","Gusti","Gustik","Gutka","Halina","Hana","Hanicka","Haninka","Hanka","Hanna","Hannelore","Hansi","Hanus","Harald","Hartmut","Hartwig","Havel","Havlik","Hedda","Hedva","Hedvicka","Hedvika","Hedwig","Heide","Heidemarie","Heidi","Heike","Heiner","Heinrich","Heinz","Hela","Helena","Helenka","Helga","Helge","Helma","Helmut","Heniuta","Henka","Henni","Henryk","Herbert","Herbertek","Herman","Hermina","Herta","Hieronim","Hilde","Hildeberta","Hildebrand","Hildegard","Holger","Holleb","Honcek","Hony","Honza","Honzak","Honzicek","Honzik","Horek","Horst","Hortenspa","Hubert","Hubertek","Hugbert","Hugo","Hynek","Ida","Ignac","Igor","Igorek","Ilja","Ilka","Ilona","Ilonka","Ilsa","Ines","Inge","Ingeborg","Ingemar","Ingrid","Irca","Irena","Irenka","Iris","Irma","Irmgard","Irmhild","Irmtraud","Isolde","Ita","Iva","Ivan","Ivana","Ivanek","Ivanka","Iveta","Ivetka","Ivka","Ivo","Ivona","Ivonka","Ivos","Ivuska","Iwona","Izabela","Izabelka","Jacek","Jachym","Jack","Jadwiga","Jadzia","Jakoubek","Jakub","Jan","Jana","Janah","Janalee","Janalyn","Janceena","Janecek","Janecska","Janek","Jania","Janica","Janicek","Janicka","Janina","Janinka","Janko","Janna","Jannah","Jannalee","Janne","Jannie","Janny","Jano","Janos","Janousek","Januarius","Jarca","Jarda","Jarek","Jarka","Jarmil","Jarmila","Jarolim","Jaromir","Jaromira","Jaroslav","Jaroslava","Jarousek","Jarunka","Jaruska","Jasia","Jasmin","Jedrek","Jedrick","Jedrik","Jedrus","Jena","Jenda","Jenicek","Jenik","Jens","Jeny","Jeronym","Jeronymek","Jindra","Jindrich","Jindrisek","Jindriska","Jira","Jiranek","Jirek","Jiri","Jiricek","Jirik","Jirina","Jirinka","Jirka","Jirousek","Jita","Jitka","Jituska","Joanka","Johana","Johanka","Johanna","Jola","Jolana","Jolanda","Jolanka","Jolanta","Jolka","Jonas","Jonasek","Jorg","Josef","Josep","Joska","Joza","Jozanek","Jozka","Judita","Juditka","Julca","Julek","Julia","Juliane","Julie","Julinka","Julius","Julka","Jura","Jurgen","Justyna","Justynka,","","Jutta","Kaca","Kacenka","Kacka","Kai","Kaja","Kajik","Kajinek","Kajinka","Kaleen","Kaleena","Kalena","Kalene","Kalina","Kamil","Kamila","Kamilia","Kamilka","Kamilla","Kamillra","Karca","Karel","Karin","Karina","Karinka","Karl","Karla","Karlheinz","Karlicek","Karlicka","Karlik","Karolin","Karolina","Karolinka","Karsten","Kasia","Kasienka","Kaska","Kaspar","Kassia","Kata","Katanyna","Katarina","Katerina","Katharina","Kathrin","Katine","Katja","Katka","Katrine","Katuska","Katy","Kaz","Kazimierz","Kazimir","Kazmer","Kelby","Kerstin","Khrystyna","Kirsten","Klara","Klarinka","Klarka","Klaudia","Klaudie","Klaus","Klement","Knut","Koby","Kolby","Konrad","Konstancji","Konstanze","Kornel","Kriemhild","Krista","Kristian","Kristin","Kristina","Kristinka","Kristof","Kristyna","Kristynka","Krysta","Krystka","Krystof","Krystufek","Krystyn","Krystyna","Krzysztof","Ksena","Kuba","Kubicek","Kubik","Kunegundy","Kunigunde","Kurt","Kveta","Kvetka","Kvetos","Kvetoslav","Kvetoslava","Kvetuse","Kvetuska","Kvido","Lada","Ladenka","Ladicek","Ladik","Ladinek","Ladislav","Ladislava","Ladka","Laduska","Laiurenty","Lara","Lars","Laura","Laurenz","Laurinka","Lea","Lechsinska","Lena","Lenicka","Lenka","Lenore","Lenz","Leo","Leon","Leona","Leonhard","Leonka","Leopold","Leos","Letta","Lia","Liana","Liba","Libek","Libena","Libenka","Libor","Liborek","Liboslav","Libuse","Libuska","Lida","Lidia","Lidka","Lidmila","Lidunka","Liduska","Liese","Lieselotte","Likla","Lila","Lili","Liliana","Lilka","Lilo","Linda","Liuz","Livia","Ljuba","Lodoiska","Lojza","Lojzek","Lojzik","Lothar","Lotte","Luba","Lubek","Lubica","Lubik","Lubomir","Lubomira","Lubor","Lubos","Lubosek","Luboslaw","Lucie","Lucinka","Lucja","Lucka","Lucyna","Luda","Ludecek","Ludek","Ludka","Ludmila","Ludmilka","Ludmilla","Ludva","Ludvik","Ludwiga","Ludwik","Luisa","Lujan","Lukas","Lukasek","Lukasz","Luki","Lulu","Lumir","Lumirek","Lydie","Mada","Madzeija","Magda","Magdalena","Magdicka","Magnar","Mahulena","Mahulenka","Majka","Majkl","Maksym","Maksymilian","Malinka","Mana","Mandek","Mandy","Manfred","Manicka","Manina","Manuela","Mara","Marcel","Marcela","Marcelka","Marcinek","Marco","Marecek","Marek","Marenka","Marfa","Margareta","Margaretha","Margisia","Margit","Margita","Maria","Marian","Mariana","Maricka","Marie","Marika","Marina","Marinka","Mario","Marius","Marjan","Marjon","Marketa","Marketka","Markus","Marlene","Maro","Marta","Marticka","Martin","Martina","Martinek","Martinka","Maruska","Marysia","Masia","Matej","Mates","Mathias","Mathilde","Matous","Matousek","Matthaus","Matyas","Matyidy","Matylda","Matysek","Maur","Maurycy","Mauty","Max","Maximilian","Maxine","Maxmilian","Medard","Meinhard","Meinhild","Mela","Melanie","Melchior","Melka","Michael","Michaela","Michal","Michala","Michalek","Miki","Mikolai","Mikolaj","Mikulas","Mikulasek","Mila","Milada","Miladka","Milan","Milanek","Milda","Milek","Milena","Milenka","Milka","Milos","Milosek","Miloslav","Miloslava","Miluse","Minka","Minna","Mirda","Mirecek","Mirek","Miriam","Mirjam","Mirka","Miron","Miroslav","Miroslava","Misa","Mitzi","Mojmir","Mojzis","Monca","Monicka","Monika","Morela","Moric","Nada","Nadenka","Nadezda","Nadine","Nadja","Nadka","Nadzia","Nastasja","Nata","Natalie","Natalka","Natasa","Natascha","Natia","Nela","Nelek","Nelinka","Nelka","Nicole","Niki","Nikodem","Nikol","Nikola","Nikolai","Nikolaus","Nikolka","Nils","Nina","Ninja","Nora","Norbert","Olda","Oldik","Oldrich","Oldriska","Oleg","Oles","Olesia","Olga","Olin","Olina","Olinka","Oliver","Olivie","Olof","Ondra","Ondrasek","Ondrej","Oskar","Oskarek","Oswald","Oswin","Ota","Otakar","Otakarek","Otik","Otmar","Oto","Ottilie","Otto","Otylia","Otylie","Otylka","Pankrac","Patricie","Patrik","Patryk","Paula","Paulina","Pauline","Pavel","Pavla","Pavlicek","Pavlicka","Pavlik","Pavlina","Pavlinka","Pawel","Pawelek","Pawl","Pepa","Pepicek","Pepik","Peta","Petka","Petr","Petra","Petricek","Petrik","Petronela","Petrusa","Petulka","Philipp","Pia","Pietrek","Piotr","Poldi","Pravoslav","Prema","Premek","Premysl","Prokop","Przemek","Przemo","Przemyslaw","Rada","Radana","Radanka","Radecek","Radek","Radim","Radimek","Radka","Radmila","Rado","Radomir","Radomira","Radoslav","Radoslava","Radoslaw","Radousek","Radovan","Radunka","Raduska","Rafal","Rahel","Raimund","Rainerreiner","Rajmund","Ralf","Randolf","Rasia","Rasine","Rastislav","Regi","Regina","Rehor","Rehorek","Reinhard","Reinhold","Renata","Renate","Renatka","Renca","Rene","Reno","Renousek","Resi","Ria","Richard","Risa","Rob","Robert","Robertek","Robin","Robo","Roch","Roland","Roman","Romana","Romanek","Romanka","Romca","Romi","Romka","Romy","Rosalinde","Rosamunde","Rosta","Rosticek","Rostik","Rostislav","Roswitha","Roz","Roza","Rozalia","Rozyuka","Ruda","Rudiger","Rudolf","Rudolfek","Rufin","Rupert","Rut","Ruza","Ruzena","Ruzenka","Ryzard","Sabin","Sabina","Sabine","Sabinka","Sabrina","Sam","Samuel","Sandra","Sara","Sarinka","Sarka","Sarlota","Sarlotka","Sasa","Saskie","Sava","Schorsch","Sebastian","Seffi","Senta","Sepp","Sergiusz","Servac","Sever","Severin","Seweryn","Siegfried","Sieghild","Sieglind","Sigrid","Sigrun","Silke","Silva","Silvestr","Silvie","Silvinka","Simca","Simon","Simona","Simone","Simonek","Simonka","Simunek","Slava","Slavek","Slavena","Slavinka","Slavka","Slavomil","Slavomir","Sobeslav","Sona","Sonicka","Sophia","Stana","Standa","Stanicek","Stanicka","Stanislav","Stanislava","Stanislaw","Stazicka","Stazka","Stefa","Stefan","Stefanie","Stefek","Steffen","Steffi","Stela","Stelinka","Stepa","Stepan","Stepanek","Stepanka","Stepek","Susanne","Svata","Svatava","Svatka","Svatopluk","Svatoslav","Svatoslava","Sven","Svetla","Svetlana","Svetlanka","Sylva","Sylvinka","Sylwia","Szczepan","Tadeas","Tamara","Tana","Tanicka","Tanja","Tatana","Tekli","Telek","Teo","Teodor","Teodory","Teodozji","Teos","Tereza","Terezka","Terinka","Terka","Tesia","Theda","Theodor","Therese","Thomas","Tibor","Till","Tim","Timo","Tobias","Tolek","Tolla","Tom","Toman","Tomanek","Tomas","Tomasek","Tomik","Tomislaw","Tonda","Tonicek","Tonicka","Tonik","Tonin","Tonka","Torsten","Traude","Traudel","Traute","Truda","Trude","Trudi","Tyna","Udo","Ulf","Ulla","Ulrich","Ulrika","Urban","Urs","Ursula","Uschi","Uta","Uwe","Vaclav","Vaclava","Valda","Valdemar","Valentina","Valentyn","Valentynek","Valerie","Vana","Vanda","Vanuska","Vasek","Vasik","Vavrik","Vavrinec","Vavrinecek","Veit","Veleslava","Vena","Venceslav","Venceslava","Venda","Vendelin","Vendula","Vendulka","Vendy","Venous","Venousek","Vera","Verca","Verka","Veronika","Veroslav","Verunka","Veruska","Viera","Vierka","Vieroslava","Viki","Viktor","Viktoria","Viktorie","Viktorka","Vilda","Vilem","Vilemek","Viliam","Vilik","Vilimek","Vilma","Vinca","Vincek","Vincenc","Vinzenz","Viola","Violka","Vit","Vitek","Vitezslav","Vlada","Vladan","Vladena","Vladenka","Vladicek","Vladik","Vladimir","Vladimira","Vladimirek","Vladinek","Vladislav","Vladislava","Vladka","Vlasta","Vlasticka","Vlastik","Vlastimil","Vlastinka","Vlastislav","Vojta","Vojtech","Vojtek","Vojtik","Vojtisek","Volkard","Volker","Vracek","Vrata","Vratislav","Walburga","Waldemar","Walerian","Waleron","Walther","Waltraud","Wendel","Wendelin","Wenzel","Werner","Weronikia","Wicus","Wienczyslaw","Wikitoria","Wikta","Wiktorja","Wilfried","Wilfrieda","Wilhelm","Wilhelmina","Wilma","Wimor","Wincent","Winfried","Wira","Wirke","Wit","Wolfgang","Wolfram","Xenie","Yachne","Yalgonata","Yveta","Yvona","Yvonne","Zan","Zaneta","Zanetka","Zanns","Zarek","Zbigniew","Zbyna","Zbynecek","Zbynek","Zbysek","Zdena","Zdenda","Zdenecek","Zdenek","Zdenicka","Zdeninka","Zdenka","Zdislav","Zdislava","Zefjm","Zelmira","Zenobia","Zikmund","Zina","Zita","Ziven","Zlata","Zlatinka","Zlatka","Zlatuska","Zocha","Zoe","Zofia","Zofie","Zofinka","Zofka","Zora","Zorinka","Zorka","Zuzana","Zuzanka","Zuzanny","Zuzi","Zuzka","Zygmunt","Zyta","Zytka"]
		let namePair = utils.getRandom(names, 2)
		return namePair.join(' ')
	}

/*

		let table = {
			1: "",
			2: "",
			3: "",
			4: "",
			5: "",
			6: "",
			7: "",
			8: "",
			9: "",
		   10: "",
		   11: "",
		   12: "",
		   13: "",
		   14: "",
		   15: "",
		   16: "",
		   17: "",
		   18: "",
		   19: "",
		   20: "",
		   21: "",
		   22: "",
		   23: "",
		   24: "",
		   25: "",
		   26: "",
		   27: "",
		   28: "",
		   29: "",
		   30: "",
		   31: "",
		   32: "",
		   33: "",
		   34: "",
		   35: "",
		   36: "",
		   37: "",
		   38: "",
		   39: "",
		   40: "",
		   41: "",
		   42: "",
		   43: "",
		   44: "",
		   45: "",
		   46: "",
		   47: "",
		   48: "",
		   49: "",
		   50: "",
		   51: "",
		   52: "",
		   53: "",
		   54: "",
		   55: "",
		   56: "",
		   57: "",
		   58: "",
		   59: "",
		   60: "",
		   61: "",
		   62: "",
		   63: "",
		   64: "",
		   65: "",
		   66: "",
		   67: "",
		   68: "",
		   69: "",
		   70: "",
		   71: "",
		   72: "",
		   73: "",
		   74: "",
		   75: "",
		   76: "",
		   77: "",
		   78: "",
		   79: "",
		   80: "",
		   81: "",
		   82: "",
		   83: "",
		   84: "",
		   85: "",
		   86: "",
		   87: "",
		   88: "",
		   89: "",
		   90: "",
		   91: "",
		   92: "",
		   93: "",
		   94: "",
		   95: "",
		   96: "",
		   97: "",
		   98: "",
		   99: "",
		  100: ""
		}

*/
	
}